spring:
  #  output:
  #    ansi:
  #      enabled: always
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        id:
          new_generator_mappings: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000

