spring:
  #  output:
  #    ansi:
  #      enabled: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        id:
          new_generator_mappings: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000

